baseURL: "https://carlosanhaya.dev/"
title: Carlos Anhaya
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: carlosanhaya.dev
  description: "Blog of carlosanhaya.dev"
  keywords: [Blog, Portfolio, PaperMod]
  author: Carlos Anhaya
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Sou programador com foco em backend

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/carlos-anhaya-460a392a/"
    - name: github
      url: "https://github.com/anhaya"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Posts
      url: archives/
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
